apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blue-green
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: deployment-2
  labels:
    app: deployment-2
spec:
  replicas: 0
  selector:
    matchLabels:
      app: deployment-2
  template:
    metadata:
      labels:
        app: deployment-2
    spec:
      containers:
        - name: example-container
          image: nginx:1.19.3
          ports:
            - containerPort: 80