apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blue-green
  name: deployment-1
  labels:
    app: deployment-1
spec:
  replicas: 0
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers:
        - name: example-container
          image: nginx:1.19.3
          ports:
            - containerPort: 80