apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blue-green
  annotations:
    # By default, the sync wave is 0, we need to set it to 1 to ensure that this resource is sync at last.
    argocd.argoproj.io/sync-wave: "2"
  name: deployment-2
  labels:
    app: deployment-2
spec:
  replicas: 0
  selector:
    matchLabels:
      app: deployment-2
  template:
    metadata:
      labels:
        app: deployment-2
    spec:
      containers:
        - name: example-container
          image: nginx:1.19.4
          ports:
            - containerPort: 80