apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: open-offer-local-applicationset
  namespace: argocd
spec:
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - app1
        - matchExpressions:
            - key: app.kubernetes.io/name
              operator: NotIn
              values:
                - app1
  generators:
    - list:
        elements:
          - name: app1
          - name: app2
  template:
    metadata:
      name: '{{name}}'
      labels:
        application.set/name: open-offer-local-applicationset
        app.kubernetes.io/name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/adrian-ramirezc/argocd-example-apps.git
        targetRevision: HEAD
        path: 'application-set/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}-ns'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - ApplyOutOfSyncOnly=true