apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: open-offer-local
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: soa-deployment
  labels:
    app: soa-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: soa-deployment
  template:
    metadata:
      labels:
        app: soa-deployment
    spec:
      containers:
        - name: example-container
          image: nginx:1.19.3
          ports:
            - containerPort: 80