apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: open-offer-local
  name: store-deployment
  labels:
    app: store-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: store-deployment
  template:
    metadata:
      labels:
        app: store-deployment
    spec:
      containers:
        - name: example-container
          image: nginx:1.19.3
          ports:
            - containerPort: 80